### ISSUE TITLE
make unpaper a shared library

### ISSUE THREAD

**Issue by thkoch2001** [Flameeyes/unpaper#5]
It would be fine, if the unpaper algorithms could me made available directly to scripting languages (python, perl) or other C programs. The first step would be to make unpaper a shared library with a separate unpaper executable that uses the library.

Second step would be to provide the language bindings.

**Comment by jflesch** [comment]
Since it might interest you : I've started working on a C/Python library containing the algorithms used by Unpaper : [libpillowfight](https://github.com/jflesch/libpillowfight). Those are rewritten + simplified versions of the algorithms (pretty much all the default values of Unpaper are hard-coded in it).
